import axios from 'axios';
import mongoose from 'mongoose';

// Models
const quizSchema = new mongoose.Schema({
  title: String,
  description: String,
  subject: String,
  teacherId: mongoose.Schema.Types.ObjectId,
  totalQuestions: Number,
  marksPerQuestion: { type: Number, default: 1 },
  duration: Number,
  studyMaterial: String,
  createdAt: { type: Date, default: Date.now }
});

const Quiz = mongoose.model('Quiz', quizSchema, 'quizzes');

const testText = `DNA (deoxyribonucleic acid) is a molecule that carries genetic instructions for life. 
It is found in the nucleus of cells and is composed of nucleotides. Each nucleotide contains three structures: 
a sugar molecule, a phosphate group, and a nitrogenous base. DNA bases are Adenine (A), Thymine (T), 
Guanine (G), and Cytosine (C). A always pairs with T, and G always pairs with C.`;

async function testQuestionGeneration() {
  try {
    console.log('\n╔════════════════════════════════════════════════════════════╗');
    console.log('║   Multi-LLM MCQ Generator - Comprehensive Test Suite        ║');
    console.log('╚════════════════════════════════════════════════════════════╝\n');

    // Step 1: Connect to MongoDB
    console.log('📦 Step 1: Connecting to MongoDB...');
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost/test');
    console.log('✅ MongoDB connected\n');

    // Step 2: Create or get a test quiz
    console.log('📝 Step 2: Creating test quiz...');
    const testTeacherId = new mongoose.Types.ObjectId();
    
    let quiz = await Quiz.findOne({ title: 'Multi-LLM Test Quiz' });
    if (!quiz) {
      quiz = await Quiz.create({
        title: 'Multi-LLM Test Quiz',
        subject: 'Biology',
        teacherId: testTeacherId,
        marksPerQuestion: 1,
        duration: 30,
        studyMaterial: testText
      });
      console.log(`✅ Created quiz: ${quiz._id}\n`);
    } else {
      console.log(`✅ Using existing quiz: ${quiz._id}\n`);
    }

    // Step 3: Test provider status
    console.log('🔍 Step 3: Checking AI Provider Status...');
    const statusResponse = await axios.get('http://localhost:9876/api/debug/ai-providers');
    console.log('Provider Order:', statusResponse.data.providerOrder);
    console.log('Provider Status:', statusResponse.data.status);
    console.log('');

    // Step 4: Generate JWT token for testing  
    console.log('🔐 Step 4: Testing MCQ Generation (without auth)...');
    console.log('   (This test uses the fallback/mixed orchestrator)\n');

    // Step 5: Generate questions
    console.log('🤖 Step 5: Generating 5 MCQs from study material...');
    console.log('   Study Material Sample: "DNA is a molecule..."');
    console.log('');

    const generateResponse = await axios.post(
      'http://localhost:9876/api/questions',
      {
        quizId: quiz._id.toString(),
        text: testText,
        numberOfQuestions: 5,
        difficulty: 'medium',
        mixedOutput: false
      },
      {
        headers: {
          'Authorization': `Bearer test-token-${Date.now()}`, // Mock token
          'Content-Type': 'application/json'
        },
        timeout: 30000
      }
    ).catch(error => {
      // Expected to fail due to auth, we'll catch and show details
      if (error.response?.status === 403) {
        console.log('⚠️  Note: Auth required for actual generation (expected)');
        console.log('   However, you can test with proper JWT token.\n');
        return null;
      }
      throw error;
    });

    if (generateResponse) {
      console.log('✅ Questions Generated Successfully!\n');
      console.log('📊 Generation Details:');
      console.log(`   Provider Used: ${generateResponse.data.provider}`);
      console.log(`   Questions Generated: ${generateResponse.data.totalGenerated}`);
      console.log(`   Fallback Used: ${generateResponse.data.fallbackUsed}`);
      console.log(`   Mixed Output: ${generateResponse.data.mixed}\n`);

      console.log('📝 Sample Question Generated:');
      const sampleQ = generateResponse.data.questions[0];
      console.log(`   Q: ${sampleQ.question}`);
      console.log(`   Generated By: ${sampleQ.generatedBy}`);
      console.log(`   Options: ${sampleQ.options.join(' | ')}`);
      console.log(`   Answer: Option ${sampleQ.correctAnswerIndex + 1}`);
    }

    console.log('\n╔════════════════════════════════════════════════════════════╗');
    console.log('║   ✅ Multi-LLM System Ready for Testing!                   ║');
    console.log('╚════════════════════════════════════════════════════════════╝\n');

    console.log('📋 Next Steps:');
    console.log('   1. Start the frontend: cd frontend && npm run dev');
    console.log('   2. Create a quiz in the UI');
    console.log('   3. Upload study material (PDF/TXT/DOCX)');
    console.log('   4. Click "Generate Questions"');
    console.log('   5. Verify Groq generates questions successfully');
    console.log('');
    console.log('🎯 Optional: Test with Ollama');
    console.log('   1. Install Ollama from https://ollama.ai');
    console.log('   2. Run: ollama serve');
    console.log('   3. Pull model: ollama pull mistral');
    console.log('   4. Generate will now fallback to Ollama if Groq fails');
    console.log('');

  } catch (error) {
    console.error('❌ Test Error:', error.message);
    if (error.response) {
      console.error('Response:', error.response.data || error.response.statusText);
    }
  } finally {
    await mongoose.disconnect();
  }
}

testQuestionGeneration();
