import axios from 'axios';

const OLLAMA_API_URL = process.env.OLLAMA_API_URL || 'http://localhost:11434';
const OLLAMA_MODEL = process.env.OLLAMA_MODEL || 'mistral';

let ollamaAvailable = null;
let resolvedOllamaModel = null;

function pickBestAvailableModel(models = []) {
  if (!models.length) return OLLAMA_MODEL;

  const names = models.map((m) => m.name).filter(Boolean);
  if (names.includes(OLLAMA_MODEL)) return OLLAMA_MODEL;

  const preferredPrefixes = ['llama2', 'mistral', 'gemma', 'qwen', 'phi'];
  for (const prefix of preferredPrefixes) {
    const match = names.find((name) => name.toLowerCase().startsWith(prefix));
    if (match) return match;
  }

  return names[0];
}

async function checkOllamaAvailability() {
  if (ollamaAvailable !== null) {
    return ollamaAvailable;
  }

  try {
    const response = await axios.get(`${OLLAMA_API_URL}/api/tags`, { timeout: 3000 });
    ollamaAvailable = response.status === 200 && (response.data.models?.length > 0 || true);
    const availableModels = response.data.models || [];
    resolvedOllamaModel = pickBestAvailableModel(availableModels);
    console.log(`[Ollama] Service available at ${OLLAMA_API_URL}. Models:`, availableModels.map(m => m.name) || []);
    console.log(`[Ollama] Using model: ${resolvedOllamaModel}`);
    return ollamaAvailable;
  } catch (error) {
    console.log(`[Ollama] Service not available at ${OLLAMA_API_URL}: ${error.message}`);
    console.log(`[Ollama] Setup Ollama: 1) Download from https://ollama.ai, 2) Run 'ollama serve', 3) Run 'ollama pull ${OLLAMA_MODEL}'`);
    ollamaAvailable = false;
    return false;
  }
}

export async function generateMCQsFromText(text, numberOfQuestions = 5) {
  try {
    const isAvailable = await checkOllamaAvailability();
    if (!isAvailable) {
      throw new Error(`Ollama service not available at ${OLLAMA_API_URL}. Ensure Ollama is running: ollama serve`);
    }

    const prompt = `Generate exactly ${numberOfQuestions} multiple-choice questions from the following text. 
Return ONLY valid JSON (no markdown, no code blocks) with this exact structure:
{
  "questions": [
    {
      "question": "Question text?",
      "options": ["Option A", "Option B", "Option C", "Option D"],
      "correctAnswer": 0,
      "explanation": "Why this is correct."
    }
  ]
}

Text: ${text}`;

    const response = await axios.post(
      `${OLLAMA_API_URL}/api/generate`,
      {
        model: resolvedOllamaModel || OLLAMA_MODEL,
        prompt,
        stream: false,
        temperature: 0.7,
      },
      { timeout: 120000 }
    );

    if (!response.data.response) {
      throw new Error('Empty response from Ollama');
    }

    const responseText = response.data.response;
    const jsonMatch = responseText.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error('No JSON found in Ollama response. Ensure Ollama model is running: ollama pull mistral');
    }

    const parsed = JSON.parse(jsonMatch[0]);
    if (!parsed.questions || !Array.isArray(parsed.questions)) {
      throw new Error('Invalid response structure from Ollama');
    }

    return parsed.questions.map(q => ({
      question: q.question,
      options: q.options,
      correctAnswer: q.correctAnswer,
      explanation: q.explanation || 'Generated by Ollama',
    }));
  } catch (error) {
    console.error('[Ollama] Error generating MCQs:', error.message);
    throw error;
  }
}

export async function generateExplanation(question, correctAnswer) {
  try {
    const isAvailable = await checkOllamaAvailability();
    if (!isAvailable) {
      throw new Error('Ollama service not available');
    }

    const prompt = `Provide a detailed explanation for this question.
Question: ${question}
Correct Answer: ${correctAnswer}

Explain why this is the correct answer (2-3 sentences):`;

    const response = await axios.post(
      `${OLLAMA_API_URL}/api/generate`,
      {
        model: resolvedOllamaModel || OLLAMA_MODEL,
        prompt,
        stream: false,
        temperature: 0.5,
      },
      { timeout: 60000 }
    );

    return response.data.response || 'No explanation available';
  } catch (error) {
    console.error('[Ollama] Error generating explanation:', error.message);
    throw error;
  }
}

export async function resetCache() {
  ollamaAvailable = null;
  resolvedOllamaModel = null;
}
